// Scripted takes. Steps before { show } are setup and never appear in the video.

// Open a couple of PRs off camera so the Recent tab has history and caches are warm.
const WARMUP = [
  { raw: 'Type "pho"' }, { raw: 'Enter' }, { sleep: 3 },
  { keys: ['ctrl+p'] }, { raw: 'Type "trace"' }, { sleep: 0.5 }, { keys: ['enter'] }, { sleep: 2.5 }, { keys: ['q'] }, { sleep: 1 },
  { keys: ['ctrl+p'] }, { raw: 'Type "jitter"' }, { sleep: 0.5 }, { keys: ['enter'] }, { sleep: 2.5 }, { keys: ['q'] }, { sleep: 1 },
  { keys: ['q'] }, { raw: 'Type "clear"' }, { raw: 'Enter' }, { sleep: 0.5 },
];

const sample = [
  { show: true },
  { sleep: 0.5 },
  { type: 'pho', speed: 110, shell: true },
  { keys: ['enter'], gap: 1.4, shell: true },
  { keys: ['tab'], gap: 0.6 },
  { keys: ['l'], gap: 0.8 },
  { keys: ['j'], gap: 0.5 },
  { keys: ['l'], gap: 0.8 },
  { keys: ['j'], gap: 0.6 },
  { keys: ['ctrl+p'], gap: 0.5 },
  { type: 'rate', speed: 120 },
  { sleep: 0.7 },
  { keys: ['enter'], gap: 3.2 },
];

const full = [
  { show: true },

  // ---- dashboard ----
  { sleep: 0.5 },
  { type: 'pho', speed: 110, shell: true },
  { keys: ['enter'], gap: 1.5, shell: true },
  { label: 'every open PR in this repo' },
  { keys: ['tab'], gap: 0.6 },
  { keys: ['j'], gap: 0.55 },
  { keys: ['j'], gap: 0.9 },
  { label: 'live preview as you move' },
  { keys: ['j'], gap: 1.1 },
  { label: 'yours · review requests · involving · all · recent' },
  { keys: ['l'], gap: 1.1 },
  { keys: ['l'], gap: 1.1 },
  { keys: ['l'], gap: 1.1 },
  { keys: ['l'], gap: 1.3 },
  { keys: ['h'], gap: 0.4 },
  { keys: ['h'], gap: 0.4 },
  { keys: ['h'], gap: 0.4 },
  { keys: ['h'], gap: 0.8 },
  { label: 'every repo you have cloned' },
  { keys: ['shift+tab'], gap: 0.6 },
  { keys: ['j'], gap: 0.5 },
  { keys: ['enter'], gap: 1.8 },
  { keys: ['shift+tab'], gap: 0.5 },
  { keys: ['j'], gap: 0.5 },
  { keys: ['enter'], gap: 1.6 },
  { keys: ['shift+tab'], gap: 0.5 },
  { keys: ['k'], gap: 0.4 },
  { keys: ['k'], gap: 0.5 },
  { keys: ['enter'], gap: 1.2 },
  { label: 'every key, one press away' },
  { keys: ['?'], gap: 2.0 },
  { keys: ['?'], gap: 0.6 },

  // ---- PR detail ----
  { label: 'jump to any PR' },
  { keys: ['ctrl+p'], gap: 0.5 },
  { type: 'rate', speed: 120 },
  { sleep: 0.6 },
  { keys: ['enter'], gap: 2.2 },
  { label: 'description, files and CI at a glance' },
  { keys: ['j'], gap: 0.3, cap: false },
  { keys: ['j'], gap: 0.3, cap: false },
  { keys: ['j'], gap: 0.3, cap: false },
  { keys: ['j'], gap: 1.4 },
  { label: 'vim keybindings in the diff' },
  { keys: ['2'], gap: 1.0 },
  { keys: ['j'], gap: 0.25 },
  { keys: ['j'], gap: 0.25 },
  { keys: ['j'], gap: 0.25 },
  { keys: ['ctrl+d'], gap: 0.7 },
  { keys: ['ctrl+d'], gap: 0.7 },
  { keys: ['g'], gap: 0.1 },
  { keys: ['g'], gap: 0.7 },
  { label: 'search the diff' },
  { keys: ['/'], gap: 0.3 },
  { type: 'burst', speed: 90 },
  { keys: ['enter'], gap: 0.8 },
  { keys: ['n'], gap: 0.6 },
  { keys: ['n'], gap: 0.8 },
  { keys: ['esc'], gap: 0.5 },
  { label: 'jump to a file' },
  { keys: ['h'], gap: 0.4 },
  ...Array(8).fill({ keys: ['j'], gap: 0.1 }),
  { keys: ['enter'], gap: 0.8 },
  { label: 'inline review comments' },
  ...Array(13).fill({ keys: ['j'], gap: 0.07, cap: false }),
  { sleep: 0.4 },
  { keys: ['space'], gap: 0.4 },
  { keys: ['j'], gap: 0.3 },
  { keys: ['j'], gap: 0.3 },
  { keys: ['j'], gap: 0.5 },
  { keys: ['c'], gap: 0.5 },
  { type: 'nit: worth a comment on why tokens is float64; fractional refill is not obvious.', speed: 28 },
  { sleep: 0.4 },
  { keys: ['enter'], gap: 1.2 },
  { label: 'review and approve' },
  { keys: ['v'], gap: 0.6 },
  { type: 'Looks solid. One nit inline, happy to ship after.', speed: 30 },
  { keys: ['enter'], gap: 2.4 },
  { keys: ['a'], gap: 0.6 },
  { type: 'Ship it', speed: 60 },
  { keys: ['enter'], gap: 1.6 },
  { label: 'reply and resolve threads' },
  { keys: ['3'], gap: 1.2 },
  { keys: ['g'], gap: 0.1 },
  { keys: ['g'], gap: 0.5 },
  { keys: ['j'], gap: 0.4 },
  { keys: ['j'], gap: 0.8 },
  { keys: ['r'], gap: 0.5 },
  { type: 'Fair. Request-based limits for v1 work for me.', speed: 30 },
  { keys: ['enter'], gap: 1.3 },
  { keys: ['m'], gap: 1.6 },
  { label: 'every commit, its own diff' },
  { keys: ['4'], gap: 1.2 },
  { keys: ['enter'], gap: 1.8 },
  { keys: ['q'], gap: 0.9 },
  { label: 'merge without leaving the terminal' },
  { keys: ['M'], gap: 0.9 },
  { keys: ['s'], gap: 0.8 },
  { keys: ['y'], gap: 3.0 },
  { keys: ['q'], gap: 0.9 },

  // ---- another repo ----
  { label: 'open a PR in another repo' },
  { keys: ['shift+tab'], gap: 0.6 },
  { keys: ['j'], gap: 0.5 },
  { keys: ['enter'], gap: 1.6 },
  { keys: ['l'], gap: 1.0 },
  { keys: ['enter'], gap: 2.0 },
  { keys: ['2'], gap: 1.2 },
  { keys: ['ctrl+d'], gap: 0.9 },
  { keys: ['ctrl+d'], gap: 1.2 },
  { keys: ['q'], gap: 0.9 },
  { keys: ['shift+tab'], gap: 0.5 },
  { keys: ['k'], gap: 0.5 },
  { keys: ['enter'], gap: 1.2 },

  // ---- create PR ----
  { label: 'open a PR from your branch' },
  { keys: ['n'], gap: 1.4 },
  { keys: ['tab'], gap: 0.3 },
  { keys: ['tab'], gap: 0.3 },
  { keys: ['tab'], gap: 0.4 },
  { keys: ['ctrl+u'], gap: 0.3 },
  { type: 'Add multipart upload to the S3 sink', speed: 45 },
  { keys: ['tab'], gap: 0.3 },
  { type: 'Objects over 64 MiB now upload in parts; failed uploads are aborted.', speed: 30 },
  { sleep: 0.4 },
  { keys: ['tab'], gap: 0.4 },
  { keys: ['ctrl+s'], gap: 2.4 },
  { keys: ['q'], gap: 1.0 },

  // ---- big PR + checkout ----
  { label: 'even 1,241-file PRs' },
  { keys: ['ctrl+p'], gap: 0.5 },
  { type: 'proto', speed: 110 },
  { sleep: 0.5 },
  { keys: ['enter'], gap: 2.2 },
  { label: 'check out any PR locally' },
  { keys: ['b'], gap: 1.8 },
  { label: 'generated files stay collapsed' },
  { keys: ['2'], gap: 1.2 },
  { keys: ['ctrl+d'], gap: 0.6 },
  { keys: ['ctrl+d'], gap: 0.6 },
  { keys: ['ctrl+d'], gap: 1.8 },
];

export const takes = {
  sample: { steps: [...WARMUP, ...sample] },
  full: { slow: 3, steps: [...WARMUP, ...full] },
};
